#!/home/chenduo/anaconda3/envs/mm/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from market_maker import my_market_maker
import market_maker
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(my_market_maker.run())
